#! /bin/sh

PROCESS_ID=$(ps x | grep 'node express-entry.js' | grep -v grep | awk '{print $1}')
if [ -z "$PROCESS_ID" ];
then
    NODE_ENV=production nohup node express-entry.js > log/$(date +"%Y-%m-%d_%H-%M-%S").log 2>&1 &
else
    echo "Server is already running"
fi
