#! /bin/sh

PROCESS_ID=$(ps x | grep 'node express-entry.js' | grep -v grep | awk '{print $1}')
if [ ! -z "$PROCESS_ID" ];
then
    pkill -9 -f 'node express-entry.js'
else
    echo "Server is not running"
fi
